adjustments:
  brightness: 1.1
  contrast: 1.2
  sharpness: 1.3
adjustments_enabled: true
blur:
  enabled: true
  height: 600
  quality: 70
  radius: 15
  subfolder: ./storage/blurred
  width: 800
input_dir: ./storage/source
max_dimensions: !!python/tuple
- 1920
- 1080
orientation_enabled: true
output_dir: ./storage/optimized
scaling_enabled: true
thumbnail:
  enabled: true
  height: 300
  quality: 70
  subfolder: ./storage/thumbnails
  width: 300
watermark:
  enabled: true
  opacity: 0.6
  padding: 20
  path: ./assets/watermark.png
  position: bottom-right
  resize_percentage: 15
webp:
  lossless: false
  method: 4
  quality: 80
