adjustments:
  brightness: 1.1
  contrast: 1.2
  sharpness: 1.3
adjustments_enabled: true
blur:
  enabled: true
  height: 800
  quality: 55
  radius: 7
  method: 3
  path: "./storage/blurred"
  width: 800
  suffix: "_blurred"
colormode: RGBA
colormode_enabled: true
input_dir: "./storage/source"
scaling:
  width: 2560
  height: 1440
orientation_enabled: true
output_dir: "./storage/optimized"
scaling_enabled: true
thumbnail:
  enabled: true
  height: 160
  quality: 55
  method: 3
  path: "./storage/thumbnails"
  width: 160
  suffix: "_tn"
watermark:
  enabled: true
  opacity: 0.75
  padding: 20
  path: "./assets/watermark.png"
  position: bottom-left
  resize_percentage: 25
webp:
  lossless: false
  method: 5
  quality: 65
