adjustments:
  brightness: 1.1
  contrast: 1.2
  sharpness: 1.3
adjustments_enabled: true
blur:
  enabled: true
  height: 800
  quality: 55
  radius: 5
  method: 4
  path: "./storage/blurred"
  width: 800
colormode: RGBA
input_dir: "./storage/source"
scaling:
  width: 1920
  height: 1080
orientation_enabled: true
output_dir: "./storage/optimized"
scaling_enabled: true
thumbnail:
  enabled: true
  height: 240
  quality: 55
  path: "./storage/thumbnails"
  width: 240
watermark:
  enabled: true
  opacity: 0.75
  padding: 20
  path: "./assets/watermark.png"
  position: bottom-left
  resize_percentage: 25
webp:
  lossless: false
  method: 6
  quality: 65
