adjustments:
  brightness: 1.1
  contrast: 1.2
  sharpness: 1.3
adjustments_enabled: true
blur:
  enabled: true
  height: 600
  quality: 70
  radius: 15
  path: "./storage/blurred"
  width: 800
input_dir: "./storage/source"
scaling:
  max_width: 1920
  max_height: 1080
orientation_enabled: true
output_dir: "./storage/optimized"
scaling_enabled: true
thumbnail:
  enabled: true
  height: 240
  quality: 55
  path: "./storage/thumbnails"
  width: 240
watermark:
  enabled: true
  opacity: 0.6
  padding: 20
  path: "./assets/watermark.png"
  position: bottom-right
  resize_percentage: 15
webp:
  lossless: false
  method: 6
  quality: 65
